import uuid

PRODUCTS = [
    # ─── DAIRY (20 products) ──────────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Full Cream Milk 1L",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Milk",
        "price": 68.0,
        "original_price": 75.0,
        "discount_percent": 9,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["milk", "dairy", "amul", "full cream"],
        "description": "Fresh full cream milk from Amul, rich in proteins and calcium.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Toned Milk 500ml",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Milk",
        "price": 32.0,
        "original_price": 35.0,
        "discount_percent": 9,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["milk", "toned milk", "amul", "dairy"],
        "description": "Amul toned milk, low fat and nutritious.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mother Dairy Full Cream Milk 1L",
        "brand": "Mother Dairy",
        "category": "Dairy",
        "subcategory": "Milk",
        "price": 66.0,
        "original_price": 70.0,
        "discount_percent": 6,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["milk", "dairy", "mother dairy", "full cream"],
        "description": "Rich and fresh full cream milk from Mother Dairy.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Butter 100g",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Butter",
        "price": 55.0,
        "original_price": 60.0,
        "discount_percent": 8,
        "rating": 4.7,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["butter", "amul", "dairy", "spreadable"],
        "description": "Classic salted Amul butter, perfect for toast and cooking.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Paneer 200g",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Paneer",
        "price": 80.0,
        "original_price": 90.0,
        "discount_percent": 11,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["paneer", "cottage cheese", "amul", "dairy"],
        "description": "Fresh and soft Amul paneer, great for curries and snacks.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Dahi 400g",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Curd",
        "price": 38.0,
        "original_price": 42.0,
        "discount_percent": 10,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["curd", "dahi", "yogurt", "amul", "dairy"],
        "description": "Creamy and fresh Amul dahi, packed with probiotics.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mother Dairy Curd 400g",
        "brand": "Mother Dairy",
        "category": "Dairy",
        "subcategory": "Curd",
        "price": 36.0,
        "original_price": 40.0,
        "discount_percent": 10,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["curd", "dahi", "mother dairy", "dairy"],
        "description": "Thick set curd from Mother Dairy, great for everyday use.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Mozzarella Cheese 200g",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Cheese",
        "price": 120.0,
        "original_price": 135.0,
        "discount_percent": 11,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["cheese", "mozzarella", "amul", "pizza", "dairy"],
        "description": "Stretchy and melty Amul mozzarella cheese, perfect for pizzas.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Britannia Cheese Slices 10pcs",
        "brand": "Britannia",
        "category": "Dairy",
        "subcategory": "Cheese",
        "price": 89.0,
        "original_price": 99.0,
        "discount_percent": 10,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["cheese", "slices", "britannia", "dairy", "sandwich"],
        "description": "Individually wrapped cheese slices ideal for sandwiches and burgers.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Ghee 1L Jar",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Ghee",
        "price": 560.0,
        "original_price": 610.0,
        "discount_percent": 8,
        "rating": 4.6,
        "in_stock": True,
        "delivery_time_mins": 18,
        "tags": ["ghee", "clarified butter", "amul", "dairy", "cooking"],
        "description": "Pure and aromatic Amul cow ghee in a resealable jar.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Nestlé MILO 400g",
        "brand": "Nestlé",
        "category": "Dairy",
        "subcategory": "Milk Mix",
        "price": 210.0,
        "original_price": 230.0,
        "discount_percent": 9,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["milo", "nestle", "chocolate malt", "dairy", "health drink"],
        "description": "Chocolate malt drink with vitamins and minerals for active kids.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Lassi 200ml",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Lassi",
        "price": 20.0,
        "original_price": 22.0,
        "discount_percent": 9,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["lassi", "buttermilk", "amul", "dairy", "sweet"],
        "description": "Chilled sweet lassi made from fresh Amul curd.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Kool Koko Flavoured Milk 200ml",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Flavoured Milk",
        "price": 25.0,
        "original_price": 28.0,
        "discount_percent": 11,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["flavoured milk", "chocolate milk", "amul", "dairy", "kool"],
        "description": "Chilled chocolate flavoured milk, a favourite among kids.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Parag Milk Ghee 500ml",
        "brand": "Parag",
        "category": "Dairy",
        "subcategory": "Ghee",
        "price": 295.0,
        "original_price": 320.0,
        "discount_percent": 8,
        "rating": 4.2,
        "in_stock": False,
        "delivery_time_mins": 18,
        "tags": ["ghee", "parag", "dairy", "cooking"],
        "description": "Pure cow ghee from Parag Milk Foods, rich in flavour.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Nestlé Greek Yogurt Strawberry 100g",
        "brand": "Nestlé",
        "category": "Dairy",
        "subcategory": "Yogurt",
        "price": 45.0,
        "original_price": 50.0,
        "discount_percent": 10,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["yogurt", "greek yogurt", "nestle", "strawberry", "dairy"],
        "description": "Thick and creamy Greek-style yogurt with strawberry flavour.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Amul Taaza Homogenised Milk 1L",
        "brand": "Amul",
        "category": "Dairy",
        "subcategory": "Milk",
        "price": 62.0,
        "original_price": 68.0,
        "discount_percent": 9,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["milk", "toned", "amul taaza", "dairy"],
        "description": "Homogenised toned milk from Amul for everyday use.",
    },

    # ─── SNACKS (22 products) ─────────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Lay's Classic Salted Chips 26g",
        "brand": "Lay's",
        "category": "Snacks",
        "subcategory": "Chips",
        "price": 20.0,
        "original_price": 20.0,
        "discount_percent": 0,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["chips", "lays", "potato chips", "snacks", "salted"],
        "description": "Crispy potato chips with classic salted flavour.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Doritos Nacho Cheese 40g",
        "brand": "Doritos",
        "category": "Snacks",
        "subcategory": "Chips",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["chips", "doritos", "nacho", "cheese", "tortilla chips"],
        "description": "Bold nacho cheese flavoured tortilla chips.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Haldiram's Aloo Bhujia 400g",
        "brand": "Haldiram's",
        "category": "Snacks",
        "subcategory": "Namkeen",
        "price": 130.0,
        "original_price": 145.0,
        "discount_percent": 10,
        "rating": 4.6,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["namkeen", "bhujia", "haldirams", "snacks", "aloo"],
        "description": "Classic crunchy Aloo Bhujia from Haldiram's, a timeless favourite.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Haldiram's Mixture 400g",
        "brand": "Haldiram's",
        "category": "Snacks",
        "subcategory": "Namkeen",
        "price": 120.0,
        "original_price": 135.0,
        "discount_percent": 11,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["mixture", "namkeen", "haldirams", "snacks", "tea time"],
        "description": "A crunchy mix of peanuts, sev, and spices from Haldiram's.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Kurkure Masala Munch 90g",
        "brand": "Kurkure",
        "category": "Snacks",
        "subcategory": "Puffed Snacks",
        "price": 20.0,
        "original_price": 20.0,
        "discount_percent": 0,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["kurkure", "snacks", "masala", "puffed", "spicy"],
        "description": "Crunchy masala puffed corn snacks with a spicy kick.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bingo Mad Angles Achaari Masti 75g",
        "brand": "Bingo",
        "category": "Snacks",
        "subcategory": "Chips",
        "price": 20.0,
        "original_price": 20.0,
        "discount_percent": 0,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["bingo", "mad angles", "chips", "achaar", "snacks"],
        "description": "Triangular chips with tangy achaari flavour.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Parle-G Biscuits 800g",
        "brand": "Parle",
        "category": "Snacks",
        "subcategory": "Biscuits",
        "price": 55.0,
        "original_price": 60.0,
        "discount_percent": 8,
        "rating": 4.7,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["parle-g", "biscuits", "parle", "snacks", "glucose biscuits"],
        "description": "India's favourite glucose biscuits, crispy and delicious.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Britannia Good Day Cashew Cookies 300g",
        "brand": "Britannia",
        "category": "Snacks",
        "subcategory": "Cookies",
        "price": 60.0,
        "original_price": 68.0,
        "discount_percent": 12,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["cookies", "cashew", "britannia", "good day", "biscuits"],
        "description": "Buttery cookies loaded with whole cashew nuts.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Oreo Original Sandwich Cookies 300g",
        "brand": "Oreo",
        "category": "Snacks",
        "subcategory": "Cookies",
        "price": 85.0,
        "original_price": 95.0,
        "discount_percent": 11,
        "rating": 4.6,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["oreo", "cookies", "chocolate", "cream", "snacks"],
        "description": "Classic chocolate sandwich cookies with sweet cream filling.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "McVitie's Digestive Biscuits 400g",
        "brand": "McVitie's",
        "category": "Snacks",
        "subcategory": "Biscuits",
        "price": 110.0,
        "original_price": 120.0,
        "discount_percent": 8,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["mcvities", "digestive", "biscuits", "wheat", "snacks"],
        "description": "Wholesome wheat biscuits, great with tea or coffee.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Maggi 2-Minute Noodles Masala 70g (5-pack)",
        "brand": "Maggi",
        "category": "Snacks",
        "subcategory": "Instant Noodles",
        "price": 75.0,
        "original_price": 80.0,
        "discount_percent": 6,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["maggi", "noodles", "instant", "masala", "snacks"],
        "description": "India's most loved instant noodles with signature masala tastemaker.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Sunfeast YiPPee Noodles 70g",
        "brand": "Sunfeast",
        "category": "Snacks",
        "subcategory": "Instant Noodles",
        "price": 14.0,
        "original_price": 15.0,
        "discount_percent": 7,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["yippee", "noodles", "instant", "sunfeast", "snacks"],
        "description": "Long and slurpy noodles that stay non-sticky for longer.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Act II Butter Popcorn 40g",
        "brand": "Act II",
        "category": "Snacks",
        "subcategory": "Popcorn",
        "price": 35.0,
        "original_price": 40.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["popcorn", "act ii", "butter", "snacks", "movie snacks"],
        "description": "Ready-to-eat buttery popcorn, perfect for movie nights.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Too Yumm Veggie Sticks 55g",
        "brand": "Too Yumm",
        "category": "Snacks",
        "subcategory": "Healthy Snacks",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["veggie sticks", "healthy snacks", "too yumm", "baked", "low fat"],
        "description": "Baked veggie sticks, a healthier alternative to chips.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Saffola Oats 1kg",
        "brand": "Saffola",
        "category": "Snacks",
        "subcategory": "Oats",
        "price": 165.0,
        "original_price": 185.0,
        "discount_percent": 11,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["oats", "saffola", "healthy", "breakfast", "rolled oats"],
        "description": "100% natural rolled oats for a healthy and filling breakfast.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "MTR Upma Mix 200g",
        "brand": "MTR",
        "category": "Snacks",
        "subcategory": "Ready Mix",
        "price": 55.0,
        "original_price": 62.0,
        "discount_percent": 11,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["upma", "mtr", "ready mix", "breakfast", "instant"],
        "description": "Ready-to-cook upma mix, just add water and temper.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Knorr Tomato Soup 42g",
        "brand": "Knorr",
        "category": "Snacks",
        "subcategory": "Soup",
        "price": 38.0,
        "original_price": 45.0,
        "discount_percent": 16,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["soup", "knorr", "tomato", "instant soup", "snacks"],
        "description": "Instant tomato soup with real tomato flavour, ready in 2 minutes.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bikano Navratan Mixture 400g",
        "brand": "Bikano",
        "category": "Snacks",
        "subcategory": "Namkeen",
        "price": 125.0,
        "original_price": 140.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["bikano", "namkeen", "mixture", "snacks", "tea time"],
        "description": "A premium blend of crunchy sev, peanuts, and spiced fried lentils.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Balaji Wafers Tomato 45g",
        "brand": "Balaji",
        "category": "Snacks",
        "subcategory": "Chips",
        "price": 20.0,
        "original_price": 20.0,
        "discount_percent": 0,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["balaji", "wafers", "tomato", "chips", "snacks"],
        "description": "Crispy potato wafers with a tangy tomato seasoning.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Hide & Seek Chocolate Chip Cookies 200g",
        "brand": "Parle",
        "category": "Snacks",
        "subcategory": "Cookies",
        "price": 60.0,
        "original_price": 68.0,
        "discount_percent": 12,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["cookies", "chocolate chip", "parle", "hide and seek", "biscuits"],
        "description": "Crispy cookies loaded with real chocolate chips.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Priyagold Butter Bite Biscuits 500g",
        "brand": "Priyagold",
        "category": "Snacks",
        "subcategory": "Biscuits",
        "price": 65.0,
        "original_price": 75.0,
        "discount_percent": 13,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["biscuits", "priyagold", "butter", "snacks", "value pack"],
        "description": "Light and buttery biscuits, great for snacking and tea time.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Lay's Magic Masala Chips 73g",
        "brand": "Lay's",
        "category": "Snacks",
        "subcategory": "Chips",
        "price": 30.0,
        "original_price": 30.0,
        "discount_percent": 0,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["chips", "lays", "magic masala", "spicy", "snacks"],
        "description": "Lay's potato chips with bold and spicy Magic Masala flavour.",
    },

    # ─── BEVERAGES (20 products) ──────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Coca-Cola 750ml PET Bottle",
        "brand": "Coca-Cola",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 40.0,
        "original_price": 45.0,
        "discount_percent": 11,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["coca cola", "coke", "cold drink", "soda", "carbonated"],
        "description": "Classic Coca-Cola refreshing carbonated soft drink.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Pepsi 2L PET Bottle",
        "brand": "Pepsi",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 90.0,
        "original_price": 99.0,
        "discount_percent": 9,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["pepsi", "cold drink", "soda", "carbonated", "2 litre"],
        "description": "Refreshing Pepsi cola in a family-size 2L bottle.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Sprite 600ml",
        "brand": "Sprite",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 40.0,
        "original_price": 45.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["sprite", "lemon lime", "soda", "cold drink", "carbonated"],
        "description": "Crisp and refreshing lemon-lime carbonated drink.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "7UP 600ml",
        "brand": "7UP",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 40.0,
        "original_price": 45.0,
        "discount_percent": 11,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["7up", "lemon", "lime", "soda", "cold drink"],
        "description": "Light and refreshing lemon-lime soft drink with zero caffeine.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Tropicana Apple Juice 1L",
        "brand": "Tropicana",
        "category": "Beverages",
        "subcategory": "Juices",
        "price": 110.0,
        "original_price": 125.0,
        "discount_percent": 12,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["juice", "apple", "tropicana", "fruit juice", "beverages"],
        "description": "100% apple juice with no added sugar, rich in natural goodness.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Real Fruit Power Orange 1L",
        "brand": "Real",
        "category": "Beverages",
        "subcategory": "Juices",
        "price": 100.0,
        "original_price": 115.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["juice", "orange", "real", "fruit juice", "beverages"],
        "description": "Refreshing orange fruit juice with pulp and natural vitamins.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Red Bull Energy Drink 250ml",
        "brand": "Red Bull",
        "category": "Beverages",
        "subcategory": "Energy Drinks",
        "price": 125.0,
        "original_price": 135.0,
        "discount_percent": 7,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["red bull", "energy drink", "caffeine", "taurine", "beverages"],
        "description": "Energy drink with caffeine, taurine and B-vitamins to boost focus.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Monster Energy Green 473ml",
        "brand": "Monster",
        "category": "Beverages",
        "subcategory": "Energy Drinks",
        "price": 130.0,
        "original_price": 145.0,
        "discount_percent": 10,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["monster", "energy drink", "caffeine", "green", "beverages"],
        "description": "Original Monster energy drink, a unique blend of flavours and energy.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bisleri Mineral Water 1L",
        "brand": "Bisleri",
        "category": "Beverages",
        "subcategory": "Water",
        "price": 20.0,
        "original_price": 20.0,
        "discount_percent": 0,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 8,
        "tags": ["water", "mineral water", "bisleri", "packaged water"],
        "description": "Pure and safe packaged drinking water from Bisleri.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Kinley Soda Water 750ml",
        "brand": "Kinley",
        "category": "Beverages",
        "subcategory": "Water",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 9,
        "tags": ["soda water", "kinley", "sparkling water", "beverages"],
        "description": "Refreshing sparkling soda water, perfect as a mixer or standalone.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Nescafé Classic Instant Coffee 50g",
        "brand": "Nescafé",
        "category": "Beverages",
        "subcategory": "Coffee",
        "price": 150.0,
        "original_price": 170.0,
        "discount_percent": 12,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["coffee", "nescafe", "instant coffee", "beverages", "hot drinks"],
        "description": "Rich and aromatic instant coffee, ready in seconds.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Tata Tea Gold 250g",
        "brand": "Tata Tea",
        "category": "Beverages",
        "subcategory": "Tea",
        "price": 130.0,
        "original_price": 145.0,
        "discount_percent": 10,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["tea", "tata tea", "gold", "chai", "beverages"],
        "description": "Premium blend of whole leaf tea for a strong and refreshing cup.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bournvita 500g",
        "brand": "Cadbury",
        "category": "Beverages",
        "subcategory": "Health Drinks",
        "price": 235.0,
        "original_price": 260.0,
        "discount_percent": 10,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["bournvita", "cadbury", "health drink", "chocolate", "beverages"],
        "description": "Chocolate malt health drink fortified with vitamins and minerals.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Horlicks Classic Malt 500g",
        "brand": "Horlicks",
        "category": "Beverages",
        "subcategory": "Health Drinks",
        "price": 275.0,
        "original_price": 305.0,
        "discount_percent": 10,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["horlicks", "malt", "health drink", "nutrition", "beverages"],
        "description": "Classic malt health drink that supports growth and immunity in kids.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Paperboat Aamras 200ml",
        "brand": "Paperboat",
        "category": "Beverages",
        "subcategory": "Juices",
        "price": 25.0,
        "original_price": 30.0,
        "discount_percent": 17,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["aamras", "mango", "paperboat", "juice", "beverages"],
        "description": "Mango pulp drink that tastes like summer, with no preservatives.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Maaza Mango 600ml",
        "brand": "Maaza",
        "category": "Beverages",
        "subcategory": "Juices",
        "price": 40.0,
        "original_price": 45.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["maaza", "mango", "juice", "beverages", "fruit drink"],
        "description": "Rich mango fruit drink with the taste of real alphonso mango.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Minute Maid Pulpy Orange 400ml",
        "brand": "Minute Maid",
        "category": "Beverages",
        "subcategory": "Juices",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["minute maid", "orange", "juice", "pulpy", "beverages"],
        "description": "Refreshing orange juice with bits of real orange pulp.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Thums Up 750ml",
        "brand": "Thums Up",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 42.0,
        "original_price": 45.0,
        "discount_percent": 7,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 10,
        "tags": ["thums up", "thumsup", "cola", "cold drink", "carbonated"],
        "description": "Strong and bold Indian cola with a unique fizzy taste.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Limca Lemon & Lime 300ml",
        "brand": "Limca",
        "category": "Beverages",
        "subcategory": "Carbonated Drinks",
        "price": 20.0,
        "original_price": 22.0,
        "discount_percent": 9,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 9,
        "tags": ["limca", "lemon lime", "soda", "cold drink", "nimbu pani"],
        "description": "Bubbly lemon-lime carbonated drink to quench your thirst.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Lipton Ice Tea Lemon 400ml",
        "brand": "Lipton",
        "category": "Beverages",
        "subcategory": "Tea",
        "price": 35.0,
        "original_price": 40.0,
        "discount_percent": 13,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["lipton", "ice tea", "lemon", "cold tea", "beverages"],
        "description": "Chilled lemon-flavoured iced tea, refreshing and low in sugar.",
    },

    # ─── FRUITS & VEGETABLES (18 products) ───────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Tomatoes 500g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 25.0,
        "original_price": 30.0,
        "discount_percent": 17,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["tomato", "fresh", "vegetables", "sabzi"],
        "description": "Farm-fresh red ripe tomatoes, ideal for curries and salads.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Onions 1kg",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 35.0,
        "original_price": 40.0,
        "discount_percent": 13,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["onion", "fresh", "vegetables", "pyaz"],
        "description": "Fresh red onions, an essential ingredient in Indian cooking.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Potatoes 1kg",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["potato", "fresh", "vegetables", "aloo"],
        "description": "Farm-fresh potatoes, versatile for any dish or snack.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Bananas 6pcs",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 40.0,
        "original_price": 48.0,
        "discount_percent": 17,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["banana", "fresh", "fruits", "kela"],
        "description": "Naturally ripened sweet bananas, rich in potassium and energy.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Shimla Apples 4pcs (~700g)",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 120.0,
        "original_price": 140.0,
        "discount_percent": 14,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["apple", "shimla", "fresh", "fruits", "seb"],
        "description": "Crispy and sweet red Shimla apples sourced directly from orchards.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Oranges 4pcs (~600g)",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 80.0,
        "original_price": 90.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["orange", "fresh", "fruits", "santra", "vitamin c"],
        "description": "Juicy and sweet oranges, packed with Vitamin C.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Spinach (Palak) 250g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Leafy Vegetables",
        "price": 20.0,
        "original_price": 25.0,
        "discount_percent": 20,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["spinach", "palak", "leafy", "fresh vegetables", "greens"],
        "description": "Tender and dark green spinach leaves, perfect for dal palak.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Carrots 500g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 35.0,
        "original_price": 40.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["carrot", "gajar", "fresh", "vegetables"],
        "description": "Crunchy and sweet carrots, great for salads, halwa, and juices.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Cauliflower (Gobhi) ~600g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 45.0,
        "original_price": 55.0,
        "discount_percent": 18,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["cauliflower", "gobhi", "fresh", "vegetables"],
        "description": "Fresh white cauliflower, ideal for sabzi and curries.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Capsicum (Green) 250g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 40.0,
        "original_price": 50.0,
        "discount_percent": 20,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["capsicum", "shimla mirch", "green", "fresh", "vegetables"],
        "description": "Crisp green capsicum, adds a fresh crunch to any dish.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Green Chilies 100g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 15.0,
        "original_price": 18.0,
        "discount_percent": 17,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["green chilli", "mirchi", "spicy", "fresh", "vegetables"],
        "description": "Fresh and pungent green chilies to add heat to your dishes.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Garlic 100g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 30.0,
        "original_price": 35.0,
        "discount_percent": 14,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["garlic", "lahsun", "fresh", "aromatic", "vegetables"],
        "description": "Fresh garlic cloves bursting with flavour and aroma.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Ginger 100g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 18.0,
        "original_price": 22.0,
        "discount_percent": 18,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["ginger", "adrak", "fresh", "aromatic", "vegetables"],
        "description": "Fresh ginger root, essential for chai and Indian cooking.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Lemons 4pcs",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 20.0,
        "original_price": 24.0,
        "discount_percent": 17,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["lemon", "nimbu", "citrus", "fresh", "fruits"],
        "description": "Juicy yellow lemons, perfect for lemonade and garnishing.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Coriander Leaves 100g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Leafy Vegetables",
        "price": 10.0,
        "original_price": 12.0,
        "discount_percent": 17,
        "rating": 4.0,
        "in_stock": True,
        "delivery_time_mins": 11,
        "tags": ["coriander", "dhania", "fresh", "herbs", "garnish"],
        "description": "Fresh fragrant coriander leaves for garnishing and cooking.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Watermelon 1 piece (~2kg)",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 99.0,
        "original_price": 120.0,
        "discount_percent": 18,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 18,
        "tags": ["watermelon", "tarbooz", "fresh", "fruits", "summer"],
        "description": "Sweet and juicy watermelon, a refreshing summer favourite.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Grapes (Green Seedless) 500g",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Fruits",
        "price": 80.0,
        "original_price": 95.0,
        "discount_percent": 16,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["grapes", "green grapes", "seedless", "fresh", "fruits"],
        "description": "Plump and sweet green seedless grapes, perfect for snacking.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Fresh Sweet Corn 2pcs",
        "brand": "Fresh",
        "category": "Fruits & Vegetables",
        "subcategory": "Vegetables",
        "price": 30.0,
        "original_price": 36.0,
        "discount_percent": 17,
        "rating": 4.1,
        "in_stock": False,
        "delivery_time_mins": 14,
        "tags": ["corn", "sweet corn", "makai", "fresh", "vegetables"],
        "description": "Fresh sweet corn ears, great for boiling, grilling, or bhutta.",
    },

    # ─── PERSONAL CARE (14 products) ─────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Dove Body Lotion 400ml",
        "brand": "Dove",
        "category": "Personal Care",
        "subcategory": "Body Lotion",
        "price": 270.0,
        "original_price": 310.0,
        "discount_percent": 13,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["dove", "body lotion", "moisturizer", "personal care", "skin"],
        "description": "Deeply moisturising body lotion with 24-hour nourishment.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Pantene Pro-V Shampoo 340ml",
        "brand": "Pantene",
        "category": "Personal Care",
        "subcategory": "Shampoo",
        "price": 265.0,
        "original_price": 299.0,
        "discount_percent": 11,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["shampoo", "pantene", "hair care", "pro-v", "personal care"],
        "description": "Pro-Vitamin formula shampoo for smooth, strong and shiny hair.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Head & Shoulders Shampoo 340ml",
        "brand": "Head & Shoulders",
        "category": "Personal Care",
        "subcategory": "Shampoo",
        "price": 260.0,
        "original_price": 299.0,
        "discount_percent": 13,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["shampoo", "head and shoulders", "anti dandruff", "hair care"],
        "description": "Anti-dandruff shampoo that gives 100% dandruff-free hair.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Colgate MaxFresh Toothpaste 150g",
        "brand": "Colgate",
        "category": "Personal Care",
        "subcategory": "Toothpaste",
        "price": 95.0,
        "original_price": 109.0,
        "discount_percent": 13,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["toothpaste", "colgate", "maxfresh", "oral care", "personal care"],
        "description": "Cooling toothpaste with micro-cooling crystals for fresh breath.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Pepsodent Germicheck Toothpaste 150g",
        "brand": "Pepsodent",
        "category": "Personal Care",
        "subcategory": "Toothpaste",
        "price": 85.0,
        "original_price": 99.0,
        "discount_percent": 14,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["toothpaste", "pepsodent", "germicheck", "antibacterial", "oral care"],
        "description": "Antibacterial toothpaste that fights germs and protects teeth.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Dettol Original Handwash 200ml",
        "brand": "Dettol",
        "category": "Personal Care",
        "subcategory": "Handwash",
        "price": 85.0,
        "original_price": 99.0,
        "discount_percent": 14,
        "rating": 4.6,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["dettol", "handwash", "antibacterial", "germ protection", "hygiene"],
        "description": "Antibacterial handwash that kills 99.9% of germs effectively.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Lifebuoy Total Soap 100g (4-pack)",
        "brand": "Lifebuoy",
        "category": "Personal Care",
        "subcategory": "Soap",
        "price": 90.0,
        "original_price": 100.0,
        "discount_percent": 10,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 12,
        "tags": ["soap", "lifebuoy", "antibacterial", "bathing bar", "hygiene"],
        "description": "Germ protection bathing soap with active silver formula.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Gillette Mach3 Razor",
        "brand": "Gillette",
        "category": "Personal Care",
        "subcategory": "Shaving",
        "price": 199.0,
        "original_price": 230.0,
        "discount_percent": 13,
        "rating": 4.6,
        "in_stock": True,
        "delivery_time_mins": 17,
        "tags": ["gillette", "razor", "mach3", "shaving", "grooming"],
        "description": "3-blade precision razor for a close and comfortable shave.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Nivea Men Face Wash 100ml",
        "brand": "Nivea",
        "category": "Personal Care",
        "subcategory": "Face Wash",
        "price": 150.0,
        "original_price": 175.0,
        "discount_percent": 14,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["face wash", "nivea", "men", "skin care", "personal care"],
        "description": "Deep cleaning face wash for men that removes dirt and oil.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Vaseline Intensive Care Lotion 200ml",
        "brand": "Vaseline",
        "category": "Personal Care",
        "subcategory": "Body Lotion",
        "price": 175.0,
        "original_price": 199.0,
        "discount_percent": 12,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["vaseline", "lotion", "moisturizer", "skin care", "personal care"],
        "description": "Fast-absorbing body lotion that heals very dry skin.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Garnier Bright Complete Moisturizer 40ml",
        "brand": "Garnier",
        "category": "Personal Care",
        "subcategory": "Moisturizer",
        "price": 165.0,
        "original_price": 190.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["garnier", "moisturizer", "face cream", "skin care", "vitamin c"],
        "description": "Vitamin C brightening moisturizer with SPF 15 sun protection.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Himalaya Neem Face Wash 150ml",
        "brand": "Himalaya",
        "category": "Personal Care",
        "subcategory": "Face Wash",
        "price": 130.0,
        "original_price": 150.0,
        "discount_percent": 13,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["himalaya", "face wash", "neem", "purifying", "acne"],
        "description": "Neem & Turmeric face wash that prevents pimples and purifies skin.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Plum E-Luminence Simply Moisturizing Lotion 150ml",
        "brand": "Plum",
        "category": "Personal Care",
        "subcategory": "Body Lotion",
        "price": 349.0,
        "original_price": 399.0,
        "discount_percent": 13,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 18,
        "tags": ["plum", "lotion", "vegan", "moisturizer", "personal care"],
        "description": "100% vegan body lotion with vitamin E and jojoba oil.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Biotique Bio Honey Gel Moisturizer 50g",
        "brand": "Biotique",
        "category": "Personal Care",
        "subcategory": "Moisturizer",
        "price": 179.0,
        "original_price": 199.0,
        "discount_percent": 10,
        "rating": 4.2,
        "in_stock": False,
        "delivery_time_mins": 16,
        "tags": ["biotique", "moisturizer", "honey", "ayurvedic", "skin care"],
        "description": "Ayurvedic honey gel moisturizer for fresh and nourished skin.",
    },

    # ─── HOUSEHOLD (14 products) ──────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "name": "Surf Excel Matic Liquid Detergent 1L",
        "brand": "Surf Excel",
        "category": "Household",
        "subcategory": "Laundry",
        "price": 275.0,
        "original_price": 310.0,
        "discount_percent": 11,
        "rating": 4.5,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["surf excel", "detergent", "liquid", "laundry", "washing machine"],
        "description": "Specially formulated liquid detergent for front-load washing machines.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Ariel Matic Powder Detergent 1kg",
        "brand": "Ariel",
        "category": "Household",
        "subcategory": "Laundry",
        "price": 230.0,
        "original_price": 260.0,
        "discount_percent": 12,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 16,
        "tags": ["ariel", "detergent", "powder", "laundry", "washing"],
        "description": "Advanced powder detergent that gives brilliant stain removal.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Vim Dishwash Bar 300g",
        "brand": "Vim",
        "category": "Household",
        "subcategory": "Dishwashing",
        "price": 35.0,
        "original_price": 40.0,
        "discount_percent": 13,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["vim", "dishwash", "bar", "utensils", "cleaning"],
        "description": "Bar detergent that cuts grease and leaves utensils sparkling clean.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Colin Glass Cleaner 500ml",
        "brand": "Colin",
        "category": "Household",
        "subcategory": "Cleaning",
        "price": 120.0,
        "original_price": 135.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["colin", "glass cleaner", "windows", "mirrors", "cleaning"],
        "description": "Streak-free glass cleaner for windows, mirrors and glass surfaces.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Lizol Floral Floor Cleaner 500ml",
        "brand": "Lizol",
        "category": "Household",
        "subcategory": "Cleaning",
        "price": 130.0,
        "original_price": 149.0,
        "discount_percent": 13,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["lizol", "floor cleaner", "disinfectant", "cleaning", "household"],
        "description": "Multi-surface floor cleaner that disinfects and leaves a fresh scent.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Harpic Power Plus Toilet Cleaner 500ml",
        "brand": "Harpic",
        "category": "Household",
        "subcategory": "Cleaning",
        "price": 110.0,
        "original_price": 125.0,
        "discount_percent": 12,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["harpic", "toilet cleaner", "cleaning", "disinfectant", "household"],
        "description": "Powerful toilet cleaner that removes stains and kills 99.9% of germs.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Domex Multi-Purpose Disinfectant 500ml",
        "brand": "Domex",
        "category": "Household",
        "subcategory": "Cleaning",
        "price": 95.0,
        "original_price": 109.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["domex", "disinfectant", "toilet cleaner", "cleaning", "household"],
        "description": "Multi-purpose bleach-based disinfectant that eliminates tough stains.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "HIT Cockroach Killer Spray 200ml",
        "brand": "HIT",
        "category": "Household",
        "subcategory": "Pest Control",
        "price": 165.0,
        "original_price": 185.0,
        "discount_percent": 11,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["hit", "cockroach killer", "pest control", "spray", "household"],
        "description": "Instant kill spray for cockroaches with long-lasting protection.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mortein All Night Electric Mosquito Liquid 45ml",
        "brand": "Mortein",
        "category": "Household",
        "subcategory": "Pest Control",
        "price": 135.0,
        "original_price": 150.0,
        "discount_percent": 10,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["mortein", "mosquito repellent", "electric", "pest control", "household"],
        "description": "All-night mosquito liquid refill for continuous protection.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Good Knight Advanced Liquid Refill 45ml",
        "brand": "Good Knight",
        "category": "Household",
        "subcategory": "Pest Control",
        "price": 100.0,
        "original_price": 115.0,
        "discount_percent": 13,
        "rating": 4.1,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["good knight", "mosquito", "repellent", "liquid refill", "pest control"],
        "description": "Fast-acting mosquito repellent liquid for uninterrupted sleep.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Scotch-Brite Scrub Pad 3pcs",
        "brand": "Scotch-Brite",
        "category": "Household",
        "subcategory": "Cleaning Supplies",
        "price": 55.0,
        "original_price": 65.0,
        "discount_percent": 15,
        "rating": 4.4,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["scotch brite", "scrub pad", "utensils", "cleaning", "household"],
        "description": "Heavy-duty scrub pads for tough grease on pans and utensils.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Odonil Bathroom Air Freshener 75g",
        "brand": "Odonil",
        "category": "Household",
        "subcategory": "Air Freshener",
        "price": 65.0,
        "original_price": 75.0,
        "discount_percent": 13,
        "rating": 4.2,
        "in_stock": True,
        "delivery_time_mins": 13,
        "tags": ["odonil", "air freshener", "bathroom", "fragrance", "household"],
        "description": "Long-lasting bathroom block that neutralises odours freshly.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Pril Power Gel Dishwash 750ml",
        "brand": "Pril",
        "category": "Household",
        "subcategory": "Dishwashing",
        "price": 120.0,
        "original_price": 140.0,
        "discount_percent": 14,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 14,
        "tags": ["pril", "dishwash", "gel", "liquid", "cleaning utensils"],
        "description": "Power gel dishwash liquid that tackles the toughest grease.",
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Comfort After Wash Fabric Conditioner 220ml",
        "brand": "Comfort",
        "category": "Household",
        "subcategory": "Laundry",
        "price": 90.0,
        "original_price": 105.0,
        "discount_percent": 14,
        "rating": 4.3,
        "in_stock": True,
        "delivery_time_mins": 15,
        "tags": ["comfort", "fabric conditioner", "softener", "laundry", "household"],
        "description": "Fabric conditioner that keeps clothes soft and fresh-smelling.",
    },
]


def get_products():
    return PRODUCTS
